version: '2'
services:
    humba-app:
        image: humba
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://humba-postgresql:5432/humba
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    humba-postgresql:
        extends:
            file: postgresql.yml
            service: humba-postgresql
